analyzers:
  pageContentAnalyzer:
    className: "UniWue\\UwA11yCheck\\Analyzers\\PageContentAnalyzer"
  newsAnalyzer:
    className: "UniWue\\UwA11yCheck\\Analyzers\\NewsAnalyzer"

checkUrlGenerators:
  page:
    className: "UniWue\\UwA11yCheck\\CheckUrlGenerators\\Page"
    configuration: {}
  pageContent:
    className: "UniWue\\UwA11yCheck\\CheckUrlGenerators\\PageContent"
    configuration: {}
  newsDetail:
    className: "UniWue\\UwA11yCheck\\CheckUrlGenerators\\NewsDetail"
    configuration: {}

presets:
  pageContent:
    name: "Check page content elements"
    description: "This check renders all content elements of the given page(s) and performs the accessibility check"
    configuration:
      baseUrl: "http://uni-wuerzburg-87.typo3.local/"
    analyzer:
      id: "pageContentAnalyzer"
      configuration: {}
    checkUrlGenerator:
      id: "pageContent"
      configuration:
        targetPid: 216467
    testSuite:
      id: "internalTests"
      tests:
        linkTextBlacklisted:
          configuration:
            blacklist: ['mehr', 'details']
  extNews:
    name: "Check ext:news records"
    description: "This check renders all news records of the given page(s) and performs the accessibility check"
    configuration:
      baseUrl: "http://uni-wuerzburg-87.typo3.local/"
    analyzer:
      id: "newsAnalyzer"
      configuration: {}
    checkUrlGenerator:
      id: "newsDetail"
      configuration:
        targetPid: 216468
    testSuite:
      id: "internalTests"
      configuration: {}

testSuites:
  internalTests:
    tests:
      linkNameTest: { name: "Link-Name", className: "UniWue\\UwA11yCheck\\Tests\\Internal\\LinkNameTest", configuration: {} }
      imageAltTest: { name: "Image-Alt", className: "UniWue\\UwA11yCheck\\Tests\\Internal\\ImageAltTest", configuration: {} }
      redundantTitle: { name: "Redundant-Title", className: "UniWue\\UwA11yCheck\\Tests\\Internal\\RedundantTitleTest", configuration: {} }
      linkTextBlacklisted: { name: "Link-Text-Blacklisted", className: "UniWue\\UwA11yCheck\\Tests\\Internal\\LinkTextBlacklistedTest", configuration: {} }
  testSuite2:
    tests:
      test1: { name: "Test 1", className: "UniWue\\UwA11yCheck\\Tests\\Test1", configuration: {} }
      test2: { name: "Test 2", className: "UniWue\\UwA11yCheck\\Tests\\Test2", configuration: {} }
