analyzers:
  internalA11yCheck:
    className: "UniWue\\UwA11yCheck\\Analyzers\\Internal"

checkUrlGenerators:
  page:
    className: "UniWue\\UwA11yCheck\\CheckUrlGenerators\\Page"
    configuration: {}
  pageContent:
    className: "UniWue\\UwA11yCheck\\CheckUrlGenerators\\PageContent"
    configuration: {}
  newsDetail:
    className: "UniWue\\UwA11yCheck\\CheckUrlGenerators\\NewsDetail"
    configuration:
      targetPid: 216468

presets:
  preset1:
    name: "A name for preset 1"
    description: "A description for the preset"
    configuration:
      baseUrl: "http://uni-wuerzburg-87.typo3.local/"
    analyzer:
      id: "internalA11yCheck"
      configuration: {}
    checkUrlGenerator:
      id: "pageContent"
      configuration:
        targetPid: 216467
    testSuite:
      id: "testSuite1"
      tests:
        image:
          configuration: {}
  preset2:
    name: "A name for preset 2"
    description: "A description for the preset"
    configuration:
      baseUrl: "http://uni-wuerzburg-87.typo3.local/"
    analyzer:
      id: "internalA11yCheck"
      configuration: {}
    checkUrlGenerator:
      id: "newsDetail"
      configuration: {}
    testSuite:
      id: "testSuite1"
      configuration: {}

testSuites:
  testSuite1:
    tests:
      linkNameTest: { name: "Link-Name", className: "UniWue\\UwA11yCheck\\Tests\\Internal\\LinkNameTest", configuration: {} }
      imageAltTest: { name: "Image-Alt", className: "UniWue\\UwA11yCheck\\Tests\\Internal\\ImageAltTest", configuration: {} }
  testSuite2:
    tests:
      test1: { name: "Test 1", className: "UniWue\\UwA11yCheck\\Tests\\Test1", configuration: {} }
      test2: { name: "Test 2", className: "UniWue\\UwA11yCheck\\Tests\\Test2", configuration: {} }
